import { useState } from "react"
import { AnimatePresence, motion } from "framer-motion"
import { ArrowUpRight, Github, X } from "lucide-react"
import { projects } from "../data/projects"
const MotionArticle = motion.article

export default function Projects() {
  const [selected, setSelected] = useState(null)
  return <section id="projects" className="section-shell section-block"><div className="section-heading section-heading-row"><div><p className="eyebrow">04 / Selected work</p><h2>Projects with a point<br /><em>of view.</em></h2></div><p className="section-lede">A few practical systems spanning machine learning, full-stack development, and data applications.</p></div><div className="project-grid">{projects.map((project, index) => <MotionArticle className={`project-card project-card-${index + 1}`} key={project.title} whileHover={{ y: -5 }} transition={{ duration: 0.2 }}><div className="project-number">0{index + 1}</div><p className="eyebrow">{project.eyebrow}</p><h3>{project.title}</h3><p className="project-description">{project.description}</p><div className="tag-row">{project.tech.map((tech) => <span className="tag" key={tech}>{tech}</span>)}</div><div className="project-actions"><button className="text-button" type="button" onClick={() => setSelected(project)}>View details <ArrowUpRight size={15} /></button><a href={project.github} target="_blank" rel="noreferrer" aria-label={`View ${project.title} on GitHub`}><Github size={17} /></a></div></MotionArticle>)}</div><AnimatePresence>{selected && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(null)}><motion.div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-title" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 18 }} onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setSelected(null)} aria-label="Close project details"><X size={19} /></button><p className="eyebrow">Project detail</p><h3 id="project-title">{selected.title}</h3><p>{selected.description}</p><ul className="detail-list">{selected.details.map((detail) => <li key={detail}>{detail}</li>)}</ul><div className="modal-actions"><a className="button button-primary" href={selected.github} target="_blank" rel="noreferrer"><Github size={16} /> GitHub</a>{selected.demo && <a className="button button-quiet" href={selected.demo} target="_blank" rel="noreferrer">Live demo <ArrowUpRight size={16} /></a>}</div></motion.div></motion.div>}</AnimatePresence></section>
}
